name: Android CI

on:
  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
    paths:
     - 'action.on' # 只有 特定 文件的更改才构建
jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
#      with:
 #       path: .Arrrknights
 #     env:
        # Set the PATH environment variable to include the folder directory
  #     PATH: $/Arrrknights/:$PATH
#       PATH: ${{ github.workspace }}/Arrrknights/:$PATH
  #     PATH: $/Arrrknights:$PATH

    - name: set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./Arrrknights
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      working-directory: ./Arrrknights
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
