name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 #     env:
        # Set the PATH environment variable to include the folder directory
  #     PATH: $/Arrrknights/:$PATH
#       PATH: ${{ github.workspace }}/Arrrknights/:$PATH
  #     PATH: $/Arrrknights:$PATH

    - name: set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x Arrrknights/gradlew
    - name: Build with Gradle
      run: ./Arrrknights/gradlew build
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: '**/*.apk'
